"""ESPHome firmware generation from a display + its hardware profile.

Emits a `display-<name>.yaml` ESP32 config modelled on the field-proven original:

  - **Power-bank keepalive:** wake every `keepalive` seconds (default 20s) just to
    draw current so a power bank doesn't auto-shut-off; only do a real Wi-Fi refresh
    every Nth wake, where N = refresh_interval / keepalive, tracked in RTC memory
    (`wake_count`) so it survives deep sleep.
  - **Raw framebuffer transport:** download the renderer's `.bin` (packed 1-bit
    framebuffer) via `esp_http_client` straight into a fixed buffer and draw it
    pixel-by-pixel — no `online_image`/PNG decode (too RAM-heavy / unreliable on
    esp32dev).
  - **keep_awake:** fetched from `/devices/<id>/status` on each real refresh; while ON
    the refresh throttle drops to every wake (fast updates for editing). Takes effect
    at the next scheduled refresh (≤ refresh_interval), since the device is asleep.

Wiring (board, SPI, pins, panel model, rotation) comes from the hardware profile's
`esphome:` block; per-display timings from an optional `device:` block. Rendered with
`@@token@@` placeholders (not str.format) so the C++ lambda braces stay literal.
"""

import os
from urllib.parse import urlparse

import render

IMAGE_PORT = int(os.environ.get("IMAGE_PORT", "5123"))
PLACEHOLDER_URL = "http://RENDERER-HOST:5123"
DEFAULT_PLATFORM = "waveshare_epaper"
DEFAULTS = {"refresh_interval": 900, "keepalive": 20, "ota_seconds": 60, "run_duration": 120,
            "keepawake_interval": 30}


class FirmwareError(ValueError):
    """Raised when a display/hardware pair can't produce firmware (missing wiring)."""


def normalize_renderer_url(raw: str) -> str:
    """Coerce a user-entered renderer address into a full base URL the ESP32 can fetch.

    Adds a missing `http://` scheme, defaults a schemeless/http address to the image
    port (:5123), leaves an explicit port or an https address (reverse proxy on 443)
    alone, and drops any stray path. Raises FirmwareError if there's no usable host.
    """
    url = raw.strip().rstrip("/")
    if "://" not in url:
        url = "http://" + url
    p = urlparse(url)
    if p.scheme not in ("http", "https") or not p.hostname:
        raise FirmwareError(f"renderer_url must look like http://host:5123 (got '{raw}')")
    port = p.port or (IMAGE_PORT if p.scheme == "http" else None)
    host = f"{p.hostname}:{port}" if port else p.hostname
    return f"{p.scheme}://{host}"


def _require(esph: dict, path: str) -> str:
    """Fetch a nested key from the hardware `esphome:` block or fail loud."""
    cur = esph
    for key in path.split("."):
        if not isinstance(cur, dict) or key not in cur:
            raise FirmwareError(f"hardware esphome block missing '{path}'")
        cur = cur[key]
    if cur in (None, ""):
        raise FirmwareError(f"hardware esphome block has empty '{path}'")
    return str(cur)


TEMPLATE = """\
# Generated by Inkwell for display '@@display_name@@'.
# Wakes every @@keepalive@@s to keep a power bank alive; does a real Wi-Fi refresh every
# @@refresh_target@@ wakes (~@@refresh_interval@@s). Set renderer_url in the add-on config, and put
# wifi_ssid/wifi_password in a secrets.yaml next to this file, then: esphome run this file.
substitutions:
  display_name: "@@display_name@@"
  renderer_url: "@@renderer_url@@"

esphome:
  name: "display-${display_name}"
  on_boot:
    priority: 200.0
    then:
      - script.execute: main_cycle

esp32:
  board: @@board@@
  framework:
    type: arduino

logger:
  level: DEBUG

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

http_request:
  useragent: "ESPHome-Display"
  timeout: 15s

deep_sleep:
  id: deep_sleep_control
  run_duration: @@run_duration@@s
  sleep_duration: @@keepalive@@s

spi:
  clk_pin: @@clk_pin@@
  mosi_pin: @@mosi_pin@@

globals:
  - id: image_data
    type: std::array<uint8_t, @@bufsize@@>
    restore_value: no
  - id: download_ok
    type: bool
    restore_value: no
    initial_value: 'false'
  # RTC memory (survives deep sleep): refresh throttle + last-known keep-awake.
  - id: wake_count
    type: int
    restore_value: true
    initial_value: '@@refresh_target@@'
  - id: keep_awake
    type: bool
    restore_value: true
    initial_value: 'false'
  # Change detection: skip the image download + e-ink refresh when the content
  # revision (from the status endpoint) matches what we last painted.
  - id: srv_rev
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: last_painted
    type: uint32_t
    restore_value: true
    initial_value: '0'

display:
  - platform: @@platform@@
    id: eink_display
    cs_pin: @@cs@@
    dc_pin: @@dc@@
    busy_pin: @@busy@@
    reset_pin: @@reset@@
    reset_duration: 2ms
    model: @@model@@
    update_interval: never
    rotation: @@rotation@@
    lambda: |-
      // Renderer packs background as bit 0, ink as bit 1. Set `invert: true` on the
      // hardware profile if the panel's black/white come out swapped (ESPHome driver
      // polarity has flipped across versions for waveshare panels).
      auto &buf = id(image_data);
      for (int y = 0; y < @@height@@; y++) {
        for (int x = 0; x < @@width@@; x++) {
          bool ink = (buf[y * @@stride@@ + x / 8] >> (7 - x % 8)) & 1;
          it.draw_pixel_at(x, y, ink ? Color::@@pixel_fg@@ : Color::@@pixel_bg@@);
        }
      }

script:
  # One refresh: poll status, and only download + repaint if the content revision
  # changed since we last painted (skips needless e-ink refreshes / downloads).
  - id: refresh_once
    mode: single
    then:
      - http_request.get:
          url: "${renderer_url}/devices/${display_name}/status"
          capture_response: true
          on_response:
            - lambda: |-
                json::parse_json(body, [](JsonObject root) -> bool {
                  id(keep_awake) = root["keep_awake"] | false;
                  id(srv_rev) = root["rev"] | 0u;
                  return true;
                });
      - if:
          condition:
            lambda: 'return id(srv_rev) != id(last_painted);'
          then:
            - logger.log:
                format: "Content changed (rev %u -> %u), downloading..."
                args: ['id(last_painted)', 'id(srv_rev)']
            - lambda: |-
                std::string url = std::string("${renderer_url}/displays/${display_name}.bin?t=") +
                                  std::to_string(millis());
                esp_http_client_config_t config = {};
                config.url = url.c_str();
                config.timeout_ms = 15000;
                config.user_agent = "ESPHome-Display";
                auto *client = esp_http_client_init(&config);
                id(download_ok) = false;
                if (client == nullptr) {
                  ESP_LOGE("main", "HTTP client init failed (heap: %d)", esp_get_free_heap_size());
                } else if (esp_http_client_open(client, 0) == ESP_OK) {
                  esp_http_client_fetch_headers(client);
                  int total = 0, chunk;
                  while (total < @@bufsize@@) {
                    int to_read = @@bufsize@@ - total;
                    if (to_read > 4096) to_read = 4096;
                    chunk = esp_http_client_read(client,
                        (char *)(id(image_data).data() + total), to_read);
                    if (chunk <= 0) break;
                    total += chunk;
                  }
                  esp_http_client_close(client);
                  if (total == @@bufsize@@) {
                    id(download_ok) = true;
                  } else {
                    ESP_LOGE("main", "Short read: %d / @@bufsize@@ bytes", total);
                  }
                } else {
                  ESP_LOGE("main", "HTTP open failed");
                }
                if (client) esp_http_client_cleanup(client);
            - if:
                condition:
                  lambda: 'return id(download_ok);'
                then:
                  - component.update: eink_display
                  - lambda: 'id(last_painted) = id(srv_rev);'
                else:
                  - logger.log: "Download failed — will retry next cycle"
          else:
            - logger.log: "No content change — skipping download + refresh"

  - id: main_cycle
    mode: single
    then:
      - lambda: |-
          // Fresh boot (power-on / reset / flash) — refresh now, don't wait out the RTC counter,
          // and force a repaint (a firmware change can alter rendering with no content change).
          if (esp_sleep_get_wakeup_cause() != ESP_SLEEP_WAKEUP_TIMER) {
            id(wake_count) = @@refresh_target@@;
            id(last_painted) = 0;
          }
          id(wake_count) += 1;
          ESP_LOGI("main", "Wake %d / %d (keep_awake=%d)", id(wake_count), @@refresh_target@@, id(keep_awake));
      - if:
          condition:
            lambda: 'return id(wake_count) >= @@refresh_target@@;'
          then:
            # --- real refresh cycle: Wi-Fi up, refresh once ---
            - lambda: 'id(wake_count) = 0;'
            - wait_until:
                wifi.connected:
            - script.execute: refresh_once
            - script.wait: refresh_once
            # keep_awake ON → genuinely stay awake, refresh every 10s until toggled off
            - if:
                condition:
                  lambda: 'return id(keep_awake);'
                then:
                  - deep_sleep.prevent: deep_sleep_control
                  - while:
                      condition:
                        lambda: 'return id(keep_awake);'
                      then:
                        - logger.log: "keep_awake — staying awake, refresh in @@keepawake_interval@@s"
                        - delay: @@keepawake_interval@@s
                        - script.execute: refresh_once
                        - script.wait: refresh_once
                  - deep_sleep.allow: deep_sleep_control
            - logger.log: "OTA window (@@ota_seconds@@s)..."
            - delay: @@ota_seconds@@s
          else:
            # --- keepalive-only wake: brief current draw, back to sleep ---
            - delay: 2s
      - logger.log: "Sleeping..."
      - deep_sleep.enter: deep_sleep_control
"""


def generate(display_name: str, renderer_url: str | None = None) -> str:
    """Render the ESPHome YAML for a display.

    `renderer_url` is the set-once add-on option (host address the ESP32 fetches from);
    falls back to a placeholder if unset. Per-display timings (`refresh_interval`,
    `keepalive`, `ota_seconds`, `run_duration`) come from the config's optional
    `device:` block.
    """
    config = render.load_display_config(display_name)
    hw = render.load_hardware(config.get("hardware", "waveshare_7in5_v2"))

    esph = hw.get("esphome")
    if not isinstance(esph, dict):
        raise FirmwareError(
            f"hardware '{config.get('hardware')}' has no esphome: block — can't generate firmware")

    width, height = int(hw["width"]), int(hw["height"])
    stride = (width + 7) // 8
    device = config.get("device") or {}
    keepalive = max(1, int(device.get("keepalive", DEFAULTS["keepalive"])))
    refresh_interval = int(device.get("refresh_interval", DEFAULTS["refresh_interval"]))

    fields = {
        "display_name": display_name,
        "renderer_url": normalize_renderer_url(renderer_url) if renderer_url else PLACEHOLDER_URL,
        "board": _require(esph, "board"),
        "clk_pin": _require(esph, "spi.clk_pin"),
        "mosi_pin": _require(esph, "spi.mosi_pin"),
        "cs": _require(esph, "pins.cs"),
        "dc": _require(esph, "pins.dc"),
        "busy": _require(esph, "pins.busy"),
        "reset": _require(esph, "pins.reset"),
        "model": _require(esph, "model"),
        "rotation": esph.get("rotation", "0°"),
        "platform": esph.get("platform", DEFAULT_PLATFORM),
        # Panel colours. With the white-background renderer convention (bg_color 255)
        # the default draws correctly on current ESPHome; set `invert: true` on the
        # hardware profile only if black/white still come out swapped on the panel.
        "pixel_fg": "WHITE" if esph.get("invert", False) else "BLACK",
        "pixel_bg": "BLACK" if esph.get("invert", False) else "WHITE",
        "width": width,
        "height": height,
        "stride": stride,
        "bufsize": stride * height,
        "refresh_interval": refresh_interval,
        "keepalive": keepalive,
        "refresh_target": max(1, refresh_interval // keepalive),
        "ota_seconds": int(device.get("ota_seconds", DEFAULTS["ota_seconds"])),
        "run_duration": int(device.get("run_duration", DEFAULTS["run_duration"])),
        "keepawake_interval": int(device.get("keepawake_interval", DEFAULTS["keepawake_interval"])),
    }
    out = TEMPLATE
    for key, val in fields.items():
        out = out.replace(f"@@{key}@@", str(val))
    return out
