"""ESPHome firmware generation from a display + its hardware profile.

Emits a `display-<name>.yaml` ESP32 config: wake from deep sleep, fetch the
rendered PNG over plain HTTP from the renderer's image port, paint it on the
e-ink panel, then sleep. The wiring (board, SPI, pins, panel model, rotation)
comes from the hardware profile's `esphome:` block; per-device settings
(`renderer_url`, `sleep_duration`) come from the display config's `device:`
block, and may be overridden per request.

Built as a text template rather than yaml.dump because ESPHome configs carry
`!secret`, `${substitutions}`, and `!lambda` blocks that don't round-trip
through a YAML serializer cleanly.
"""

import os
from urllib.parse import urlparse

import render

IMAGE_PORT = int(os.environ.get("IMAGE_PORT", "5123"))
DEFAULT_SLEEP = "15min"
# Emitted when no renderer_url is configured — a valid substitution string, so
# `esphome config` still passes; the user swaps it for their renderer's LAN address.
PLACEHOLDER_URL = "http://RENDERER-HOST:5123"
DEFAULT_PLATFORM = "waveshare_epaper"
DEFAULT_IMAGE_TYPE = "BINARY"  # 1-bit PNG (color_mode "1"); color panels differ (deferred)


class FirmwareError(ValueError):
    """Raised when a display/hardware pair can't produce firmware (missing wiring)."""


def normalize_renderer_url(raw: str) -> str:
    """Coerce a user-entered renderer address into a full base URL the ESP32 can fetch.

    Adds a missing `http://` scheme, defaults a schemeless/http address to the image
    port (:5123), leaves an explicit port or an https address (reverse proxy on 443)
    alone, and drops any stray path. Raises FirmwareError if there's no usable host.
    """
    url = raw.strip().rstrip("/")
    if "://" not in url:
        url = "http://" + url
    p = urlparse(url)
    if p.scheme not in ("http", "https") or not p.hostname:
        raise FirmwareError(
            f"renderer_url must look like http://host:5123 (got '{raw}')")
    port = p.port or (IMAGE_PORT if p.scheme == "http" else None)
    host = f"{p.hostname}:{port}" if port else p.hostname
    return f"{p.scheme}://{host}"


def _require(esph: dict, path: str) -> str:
    """Fetch a nested key from the hardware `esphome:` block or fail loud."""
    cur = esph
    for key in path.split("."):
        if not isinstance(cur, dict) or key not in cur:
            raise FirmwareError(f"hardware esphome block missing '{path}'")
        cur = cur[key]
    if cur in (None, ""):
        raise FirmwareError(f"hardware esphome block has empty '{path}'")
    return str(cur)


TEMPLATE = """\
# Generated by Inkwell for display '{display_name}'.
# Set renderer_url to your renderer's LAN address and provide wifi_ssid/wifi_password
# in a secrets.yaml next to this file, then: esphome run display-{display_name}.yaml
substitutions:
  display_name: "{display_name}"
  renderer_url: "{renderer_url}"
  sleep_duration: "{sleep_duration}"

esphome:
  name: "display-${{display_name}}"
  on_boot:
    priority: 200.0
    then:
      - script.execute: main_cycle

esp32:
  board: {board}
  framework:
    type: arduino

logger:
  level: DEBUG

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

http_request:
  useragent: "ESPHome-Display"
  timeout: 15s

deep_sleep:
  id: deep_sleep_control
  run_duration: 90s
  sleep_duration: ${{sleep_duration}}

spi:
  clk_pin: {clk_pin}
  mosi_pin: {mosi_pin}

online_image:
  - url: "${{renderer_url}}/displays/${{display_name}}.png"
    id: menu_image
    format: PNG
    type: {image_type}
    resize: {width}x{height}
    on_download_finished:
      - component.update: eink_display
      - logger.log: "OTA window (10s)..."
      - delay: 10s
      - deep_sleep.enter: deep_sleep_control
    on_error:
      - logger.log: "Image download failed, sleeping"
      - delay: 10s
      - deep_sleep.enter: deep_sleep_control

display:
  - platform: {platform}
    id: eink_display
    cs_pin: {cs}
    dc_pin: {dc}
    busy_pin: {busy}
    reset_pin: {reset}
    reset_duration: 2ms
    model: {model}
    update_interval: never
    rotation: {rotation}
    lambda: |-
      it.image(0, 0, id(menu_image));

script:
  - id: main_cycle
    mode: single
    then:
      - wait_until:
          wifi.connected:
      - logger.log: "Downloading image from renderer..."
      - online_image.set_url:
          id: menu_image
          url: !lambda |-
            return std::string("${{renderer_url}}/displays/${{display_name}}.png?t=") +
                   std::to_string(millis());
"""


def generate(display_name: str, renderer_url: str | None = None) -> str:
    """Render the ESPHome YAML for a display.

    `renderer_url` is the set-once add-on option (host address the ESP32 fetches from);
    falls back to a placeholder if unset. `sleep_duration` is per-display via the config's
    optional `device:` block."""
    config = render.load_display_config(display_name)
    hw = render.load_hardware(config.get("hardware", "waveshare_7in5_v2"))

    esph = hw.get("esphome")
    if not isinstance(esph, dict):
        raise FirmwareError(
            f"hardware '{config.get('hardware')}' has no esphome: block — can't generate firmware")

    device = config.get("device") or {}
    return TEMPLATE.format(
        display_name=display_name,
        renderer_url=normalize_renderer_url(renderer_url) if renderer_url else PLACEHOLDER_URL,
        sleep_duration=device.get("sleep_duration") or DEFAULT_SLEEP,
        board=_require(esph, "board"),
        clk_pin=_require(esph, "spi.clk_pin"),
        mosi_pin=_require(esph, "spi.mosi_pin"),
        cs=_require(esph, "pins.cs"),
        dc=_require(esph, "pins.dc"),
        busy=_require(esph, "pins.busy"),
        reset=_require(esph, "pins.reset"),
        model=_require(esph, "model"),
        rotation=esph.get("rotation", "0°"),
        platform=esph.get("platform", DEFAULT_PLATFORM),
        image_type=esph.get("image_type", DEFAULT_IMAGE_TYPE),
        width=int(hw["width"]),
        height=int(hw["height"]),
    )
